class Robot:
    def __init__(self, json):
        self.id: int = json.get("id")
        self.player_id: int = json.get("player_id")
        self.is_teammate: bool = json.get("is_teammate")
        self.x: float = json.get("x")
        self.y: float = json.get("y")
        self.z: float = json.get("z")
        self.velocity_x: float = json.get("velocity_x")
        self.velocity_y: float = json.get("velocity_y")
        self.velocity_z: float = json.get("velocity_z")
        self.radius: float = json.get("radius")
        self.nitro_amount = json.get("nitro_amount")
        self.touch = json.get("touch")
        self.touch_normal_x: float = json.get("touch_normal_x")
        self.touch_normal_y: float = json.get("touch_normal_y")
        self.touch_normal_z: float = json.get("touch_normal_z")
