#ifndef MYSTRATEGY_CONST_H
#define MYSTRATEGY_CONST_H

#define UCT_K 1.41421
#define UTC_MAX_ITERATIONS 1000
#define UTC_SIMULATION_DEPTH 1
#define SIMULATION_DT 0.05
#define SIMULATION_PLAYOUT_DT 0.1

#define MAX_ACTIONS 19
//#define MY_DEBUG 1

#endif //MYSTRATEGY_CONST_H
