#ifndef MYSTRATEGY_CONST_H
#define MYSTRATEGY_CONST_H

#define UCT_K 1.41421
#define UTC_MAX_ITERATIONS 5000
#define UTC_SIMULATION_DEPTH 1

#define MAX_ACTIONS 19
#define MY_DEBUG 0

#endif //MYSTRATEGY_CONST_H
